"""
Each new term in the Fibonacci sequence
is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci 
sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
"""


def fib(n):
    sum = 0
    num1, num2 = 0, 1

    while True:
        term = num1 + num2
        num1 = num2
        num2 = term

        if term % 2 == 0:
            if term < n:
                sum += term
            else:
                print("Final sum:", sum)
                break

fib(4000000)

"---Solved---"
"Answer: 4613732"